### ISSUE TITLE
「定常的に繰り返し実施」ページに「。」が連続している箇所がある

### ISSUE THREAD

**Issue by ikoga** [nttcom/onboarding-handbook#6]
定常的に繰り返し実施 `regular-basis.md` ページの 50行目の末尾に、「。」が連続している箇所がありました。    
https://github.com/nttcom/onboarding-handbook/blame/main/content/docs/regular-basis.md#L50

> (略) 軌道修正を早いタイミングで実施することで、新メンバーでも成果をだせます。 。   

これが意図的な表現でなければ、「。」は 1つ不要だと思います。

**Comment by iwashi** [comment]
コメントいただきありがとうございます。タイポですので修正いたします。
