### ISSUE TITLE
「配属前」>「トレーナー、メンターのアサイン」に誤字がある

### ISSUE THREAD

**Issue by ky-yk-d** [nttcom/onboarding-handbook#8]
https://github.com/nttcom/onboarding-handbook/blob/c70e7b82842b929482ab125b8cdeb487c6c788c3/content/docs/pre.md

> 配属された新メンバーが、業務を進めるていると必ず何らかの困りごとが発生します。

（誤）業務を進めるている
（正）業務を進めている

かと思われます。

**Comment by iwashi** [comment]
@ky-yk-d ありがとうございます。修正いたします。
